INSERT INTO ENGINE(ENGINE_TYPE) VALUES('gas');
INSERT INTO ENGINE(ENGINE_TYPE) VALUES('diesel');
INSERT INTO ENGINE(ENGINE_TYPE) VALUES('hybrid');

INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Volvo',1,2018);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Mercedes',1,2019);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Nissan',2,2016);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Porsche',3,2018);