CREATE TABLE CAR(
    CAR_ID IDENTITY NOT NULL PRIMARY KEY,
    CAR_BRAND VARCHAR NOT NULL,
    CAR_ENGINE_FK INT NOT NULL,
    CAR_YEAR INT NOT NULL
);
CREATE TABLE ENGINE(
    ENGINE_ID IDENTITY NOT NULL PRIMARY KEY,
    ENGINE_TYPE VARCHAR NOT NULL
);

 ALTER TABLE CAR
    ADD FOREIGN KEY (CAR_ENGINE_FK) 
    REFERENCES ENGINE(ENGINE_ID);

INSERT INTO ENGINE(ENGINE_TYPE) VALUES('gas');
INSERT INTO ENGINE(ENGINE_TYPE) VALUES('diesel');
INSERT INTO ENGINE(ENGINE_TYPE) VALUES('hybrid');

INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Volvo',1,2018);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Mercedes',1,2019);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Nissan',2,2016);
INSERT INTO CAR(CAR_BRAND,CAR_ENGINE_FK,CAR_YEAR) VALUES('Porsche',3,2018);

