DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS ENGINE;

CREATE TABLE CAR(
    CAR_ID IDENTITY NOT NULL PRIMARY KEY,
    CAR_BRAND VARCHAR NOT NULL,
    CAR_ENGINE_FK INT NOT NULL,
    CAR_YEAR INT NOT NULL
);
CREATE TABLE ENGINE(
    ENGINE_ID IDENTITY NOT NULL PRIMARY KEY,
    ENGINE_TYPE VARCHAR NOT NULL
);

 ALTER TABLE CAR
    ADD FOREIGN KEY (CAR_ENGINE_FK)
    REFERENCES ENGINE(ENGINE_ID);